### ISSUE TITLE
Project SR-1: correctness of the mapped data (Table Facts-categorie)

### ISSUE THREAD

**Issue by cochardjl** [zazuko/data-cube-curation#214]
I checked the result of the mapped data from the table Facts-categorie and I was not completey okay with the generated triples.

For each fact I have a predicate "dim1" that must refer to a dimensional entity .../dim1/1.
The mapping is done but the raw value of the column (dim1) in the table Facts (= 1 as integer) is kept as an additional triple for this fact.
I think it should be skipped once the mapping is done. 
For the dim2 and dim3 for which no mapping is defined, I understand that the raw are mentioned but not for dim1.

I'm not sure this explanation is clear but have a look at the mapped data and it should be clearer. If still not, contact me directly.

Jean-Luc

**Comment by martinmaillard** [comment]
The "dim1" integer value is present in the triples because "dim1" is also defined as an integer property/attribute (in addition to the "link to the Dim1 table"). Removing the attribute should solve your issue.

<img width="1413" alt="Screenshot 2020-02-05 at 14 00 33" src="https://user-images.githubusercontent.com/1334124/73844118-34c99180-4820-11ea-83d8-9491e19d9e9e.png">

**Comment by cochardjl** [comment]
Thanks! Clear

**Comment by tpluscode** [comment]
Thank you for answering @martinmaillard. Closing then
